### ISSUE TITLE
null exception: http://localhost/bibliographicResources?dct:title=hello

### ISSUE THREAD

**Issue by guenterh** [linked-swissbib/hydra-swissbib.ch#1]
@maechler Hi Markus,
ich habe die ES Adresse in der Konfiguration, wie in Deinem letzten mail geschrieben, neu gesetzt
(    elastic_search.hosts: ["http://sb-s2.swissbib.unibas.ch:8080"])
Das war aber wohl nicht das Problem für die null exception beim Aufrif der Adresse wie im subject
Man bekommt die Fehlermeldung auch, wenn man 
http://data.swissbib.ch/bibliographicResources?dct:title=hello 
aufruft.
Ich bin dem mal nachgegangen. Das Problem siehts Du im screenshot.
Günter
![exception bibliographic ressource](https://cloud.githubusercontent.com/assets/1825990/18504825/927139ba-7a64-11e6-9dbd-4288279b22ef.png)

**Comment by maechler** [comment]
Hallo Günter

Besten Dank für die Analyse. Collections sind wie gesagt noch nicht unterstützt. Deshalb landest du hier im CollectionDataProvider von Doctrine. Da unser ElasticsearchDataProvider Collections noch nicht unterstützt. 
Was allerdings funktionieren sollte sind abfragen auf einzelne Konzepte: 
http://data.swissbib.ch/items/ABN-30721838-3954-3cc9-88fe-96f1eb279f1b
